version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install -r tests/requirements.txt
      - curl -LO https://releases.hashicorp.com/terraform/1.12.0/terraform_1.12.0_linux_amd64.zip
      - unzip terraform_1.12.0_linux_amd64.zip -d /usr/local/bin/
  pre_build:
    commands:
      - echo "Running terraform checks..."
      - terraform init
      - terraform fmt -check
      - terraform validate
  build:
    commands:
      - echo "Running unit tests..."
      - pytest tests/
  post_build:
    commands:
      - echo "Build phase complete."

artifacts:
  files:
    - 'infrastructure/**'